import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class LocationListProvider {
  private readonly locationList : Array<Location> = [
    { id: 1, name: 'Route 1' },
    { id: 2, name: 'Route 2' },
    { id: 3, name: 'Route 3' },
    { id: 4, name: 'Route 4' },
    { id: 5, name: 'Route 5' },
    { id: 6, name: 'Route 6' },
    { id: 7, name: 'Route 7' },
    { id: 8, name: 'Route 8' },
    { id: 9, name: 'Route 9' },
    { id: 10, name: 'Route 10' },
    { id: 11, name: 'Route 11' },
    { id: 12, name: 'Route 12' },
    { id: 13, name: 'Route 13' },
    { id: 14, name: 'Route 14' },
    { id: 15, name: 'Route 15' },
    { id: 16, name: 'Route 16' },
    { id: 17, name: 'Route 17' },
    { id: 18, name: 'Route 18' },
    { id: 19, name: 'Route 19' },
    { id: 20, name: 'Route 20' },
    { id: 21, name: 'Route 21' },
    { id: 22, name: 'Route 22' },
    { id: 23, name: 'Route 23' },
    { id: 24, name: 'Abundant Shrine' },
    { id: 25, name: 'Accumula Town' },
    { id: 26, name: 'Anville Town' },
    { id: 27, name: 'Aspertia City' },
    { id: 28, name: 'Battle Subway' },
    { id: 29, name: 'Black City' },
    { id: 30, name: 'Castelia City' },
    { id: 31, name: 'Castelia Sewers' },
    { id: 32, name: 'Cave of Being' },
    { id: 33, name: 'Celestial Tower' },
    { id: 34, name: 'Challenger\'s Cave' },
    { id: 35, name: 'Chargestone Cave' },
    { id: 36, name: 'Clay Tunnel' },
    { id: 37, name: 'Cold Storage' },
    { id: 38, name: 'Desert Resort' },
    { id: 39, name: 'Dragonspiral Tower' },
    { id: 40, name: 'Dreamyard' },
    { id: 41, name: 'Driftveil City' },
    { id: 42, name: 'Driftveil Drawbridge' },
    { id: 43, name: 'Floccesy Ranch' },
    { id: 44, name: 'Floccesy Town' },
    { id: 45, name: 'Gear Station' },
    { id: 46, name: 'Giant Chasm' },
    { id: 47, name: 'High Link' },
    { id: 48, name: 'Humilau City' },
    { id: 49, name: 'Icirrus City' },
    { id: 50, name: 'Lacunosa Town' },
    { id: 51, name: 'Lentimas Town' },
    { id: 52, name: 'Liberty Island' },
    { id: 53, name: 'Lostlorn Forest' },
    { id: 54, name: 'Marine Tube' },
    { id: 55, name: 'Marvelous Bridge' },
    { id: 56, name: 'Mistralton Cave' },
    { id: 57, name: 'Mistralton City' },
    { id: 58, name: 'Moor of Icirrus' },
    { id: 59, name: 'N\'s Castle' },
    { id: 60, name: 'Nacrene City' },
    { id: 61, name: 'Nature Preserve' },
    { id: 62, name: 'Nature Sanctuary' },
    { id: 63, name: 'Nimbasa City' },
    { id: 64, name: 'Nuvema Town' },
    { id: 65, name: 'Opelucid City' },
    { id: 66, name: 'P2 Laboratory' },
    { id: 67, name: 'Pinwheel Forest' },
    { id: 68, name: 'Plasma Frigate' },
    { id: 69, name: 'Pledge Grove' },
    { id: 70, name: 'Pokémon League' },
    { id: 71, name: 'Pokémon World Tournament' },
    { id: 72, name: 'Relic Castle' },
    { id: 73, name: 'Relic Passage' },
    { id: 74, name: 'Reversal Mountain' },
    { id: 75, name: 'Roaming Unova' },
    { id: 76, name: 'Seaside Cave' },
    { id: 77, name: 'Skyarrow Bridge' },
    { id: 78, name: 'Strange House' },
    { id: 79, name: 'Striaton City' },
    { id: 80, name: 'Tubeline Bridge' },
    { id: 81, name: 'Twist Mountain' },
    { id: 82, name: 'Undella Bay' },
    { id: 83, name: 'Undella Town' }, 
    { id: 84, name: 'Underground Ruins' },
    { id: 85, name: 'Undersea Ruins' },
    { id: 86, name: 'Unity Tower' },
    { id: 87, name: 'Victory Road' },
    { id: 88, name: 'Village Bridge' },
    { id: 89, name: 'Virbank City' },
    { id: 90, name: 'Virbank Complex' },
    { id: 91, name: 'Wellspring Cave' },
    { id: 92, name: 'White Forest' }
  ];

  public getLocationList() : Array<Location> {
    return this.locationList;
  }
}

export interface Location {
  id : number;
  name : string;
}